### ISSUE TITLE
{#design-transitions}: Is it true that only `execution::schedule` can create a sender that will move execution to a specific execution context?

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/stdexec#106]
We have this sentence in {#design-transitions}:

> The only operation that can create a sender that will move execution to a *specific* execution context is `execution::schedule`.

Is that true? What about `execution::reschedule`?

**Comment by mjgarland** [comment]
I think the statement you quoted is referring to the state of affairs in P0443r14, by way of justifying the need for additional algorithms like `transfer` f.k.a. `reschedule` in P2300.
