### ISSUE TITLE
More MSVC cl and clang-cl fixes

### ISSUE THREAD

**Issue by lukester1975** [NVIDIA/stdexec#1107]
Hi

There are few cl/clang-cl issues I've tripped over after #1061 (with VS17.8pre3):

* clang-cl doesn't yet implement `[[msvc::no_unique_address]]` (https://reviews.llvm.org/D110485), so things are currently very noisy (`warning : unknown attribute 'no_unique_address' ignored [-Wunknown-attributes]`) especially with the levels of expansion of `STDEXEC_ATTRIBUTE`...
* `test_iterate` doesn't build; missing a `<numeric>` include for `std::accumulate`
* `__allocator` is a #define in Windows SDK's shared/specstrings.h, so triggers `stdexec/execution.hpp(273,25): error : expected unqualified-id`. Maybe it's worth `#include <windows.h>` in a test(s) to highlight that? I've just hackily renamed the [concept](https://github.com/NVIDIA/stdexec/blob/a5c350f8e3751c4cc110494ee5ab3f555d991a04/include/stdexec/execution.hpp#L266-L268) to `__allocator_c`.

Anyway all trivial but if it's any use: https://github.com/lukester1975/stdexec/tree/win-fixes

HTH

Thanks!

**Comment by maikel** [comment]
Cool! I think it would help if you could open a PR with your branch. Is it possible for you?

Thank you for your notes
