### ISSUE TITLE
stdexec and P3109

### ISSUE THREAD

**Issue by laramiel** [NVIDIA/stdexec#1254]
Hello-

Based on [P3109](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p3109r0.html), there are a few pending changes to `std::execution`. The most invasive change appears to be removal of tag_invoke. Is there a branch where this work is/will take place?

**Comment by ericniebler** [comment]
The paper proposing to replace `tag_invoke` is P2855, the most up-to-date version o which can be found here: https://isocpp.org/files/papers/D2855R1.html

Ville's implementation is a work in progress. It lives here:
https://github.com/villevoutilainen/wg21_p2300_std_execution/tree/P2855_member_customization_points
