### ISSUE TITLE
compilation error- reference to 'connect' is ambiguous

### ISSUE THREAD

**Issue by abhilashraju** [NVIDIA/stdexec#1269]
Got compilation error for [connect] (https://godbolt.org/z/37ob4zzWv) .
This can be fixed with change in the inclusion order. Is that expected?

**Comment by maikel** [comment]
No its not expected. This particular error usually comes from an improper use of an unqualified call to connect in the exec namespace. There is a very popular C function called connect whenever networking is involved.

We probably need an issue to fully qualify all uses of CPO from within (nv)exec namespace.
