### ISSUE TITLE
{#design-sender-adaptor-split}: Rename `split` to `then_all`

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/stdexec#133]
> We could rename "split" -> "then_all" so you get "when_all" and "then_all" as mirrors of each other

Suggestions from @ogiroux

**Comment by LeeHowes** [comment]
It wouldn't be symmetric with `when_any` though, unless we want a nondeterministic `then_any` as well?

I'm not sure about `then` in any case - it's inconsistent with the `std::optional` monadic proposal among other things.
