### ISSUE TITLE
{#design-sender-adaptor-then}: Naming of `then` and the difference between task and data models

### ISSUE THREAD

**Issue by kirkshoop** [NVIDIA/stdexec#135]
`then` and `transform` represent different mental models that will affect algorithm design and teaching and program correctness.
- `then` describes an algorithm to create a sequence of tasks.
- `transform` describes an algorithm to change argument values into a result value.

`then` follows a task model. In a task model, side-effects and manual synchronization are expected. Code structured around this mental model will fail in all the same ways that thread and manual synchronization models have always failed. We gain very little by cementing another task mental model into std.

`transform` follows a data model. In a data model, side-effects are discouraged and considered harmful. The function passed to transform should be flagged in code-review when it has side-effects. In a data model, manual synchronization is anathama. Code structured around a data model is far less subject to the failures of the task model because it specifies the behaviour of the interface (concepts) such that the task model is an implementation-detail that is not exposed.

**Comment by brycelelbach** [comment]
`transform` is the name of an existing sequence algorithm in the Standard Library. The existing `transform` in `std::` may be conceptually similar to `then`, but it has a very different interface and different semantics.

`transform` may be the right name for this algorithm in a vacuum, but calling it `transform` would unnecessarily collide with an existing term and cause confusion for both users and the committee.

I'm open to other names, but fairly strongly opposed to `transform`.

**Comment by kirkshoop** [comment]
Other names that are used in existing libraries are `map` and `select`

If the semantics differences are sequence vs single, I would question whether we want the multisender to use a different name for this algo? It would seem that making this distinction would affect teaching by having multiple names for the same thing and have the differences between those things be subtle 0..N vs 0..1
