### ISSUE TITLE
stdexec CMake turns off BUILD_TESTING for developer projects

### ISSUE THREAD

**Issue by stephenberry** [NVIDIA/stdexec#1365]
Using CPMAddPackage or FetchContent_Declare with stdexec will cause the `CTest` `BUILD_TESTING` value to be turned off. This disables unit tests or GitHub actions when stdexec is added as a dependency to other projects.

**Comment by ericniebler** [comment]
@stephenberry can you see if #1366 fixes your issue?

**Comment by stephenberry** [comment]
@ericniebler
Yes, https://github.com/NVIDIA/stdexec/pull/1366 fixes the issue. Thanks!
