### ISSUE TITLE
Consider integrating the ideas from P2257R0 to add a blocking query

### ISSUE THREAD

**Issue by lewissbaker** [NVIDIA/stdexec#140]
The paper [P2257R0](https:// suggested adding the `get_blocking()` query for an operation-state to allow querying whether or not the operation will complete synchronously, asynchronously or with unknown disposition.

We should consider adding something equivalent to the design to cover some of the functionality that was removed from P0443 - namely the `blocking` property.

The use of such a query can be useful for implementing optimisations of certain algorithms, e.g. by allowing placement operation-state objects on the stack instead of on the heap when the operations will complete synchronously.

**Comment by griwes** [comment]
On Wednesday we decided that for R1 we're going to do #138, and then we'll figure out something that's probably generic across many operations for R2. It's not just the operation state we may need to ask, but essentially any customization point on any object it is valid for, I think (or at least any maybe-eager customization point).

**Comment by ericniebler** [comment]
moved to cplusplus/sender-receiver#60
