### ISSUE TITLE
`continue/start_on` vs `continues/starts_on` naming

### ISSUE THREAD

**Issue by msimberg** [NVIDIA/stdexec#1410]
P2300 seems to have moved to `continues/starts_on`, while stdexec is using `continue/start_on`. P2300 is correct, no? I'd just like to confirm for compatibility and renamings in pika (which is still calling it `transfer`). If they should be called `continues/starts_on` in stdexec I'd happily do the rename as well here (probably with an alias to `continue/start_on`).

**Comment by ericniebler** [comment]
stdexec hasn't yet adopted the new names. if you make a pr to add the new names (tia!), pls leave the old names as (deprecated) aliases so we don't break code.
