### ISSUE TITLE
`stdexec::split` does not work with `any_sender_of`

### ISSUE THREAD

**Issue by romintomasetti** [NVIDIA/stdexec#1411]
My goal is to add senders in a diamond-like graph depending on a runtime condition.

I see 2 ways of implementing this:
1. Nest whatever your conditional work is in a `then` that checks if the work needs to be done. This means the "wrapping" sender can be added with fully-specified templated types. Whatever the runtime conditionals, we always have a fixed amount of senders in the chain. 
2. Conditionally add the sender and use "any" senders to deal with the work being added in the chain or not. Depending on the runtime conditionals, we have a varying amount of senders in the chain.

I prefer solution 2.

Since I want a diamond pattern, I need to use `stdexec::split` to ensure that the top node runs only once.

However, `stdexec::split` does not play well with "any" senders (compiler error). Is it intended or a bug ?

Here is a reproducer. The node A will execute twice because `| stdexec::split();` prevents the code from compiling.
```c++
template <char ID>
struct Greetings {
    void operator()() const noexcept { printf("Greetings from %c.\n", ID); }
};

template <class... Ts>
using any_sender_of =
  typename ::exec::any_receiver_ref<::stdexec::completion_signatures<Ts...>>::template any_sender<>;

//! Inspired by https://github.com/NVIDIA/stdexec/blob/8bc7c7f06fe39831dea6852407ebe7f6be8fa9fd/examples/benchmark/fibonacci.cpp.
TEST(try, it)
{
    stdexec::sender auto node_A = stdexec::just() | stdexec::then(Greetings<'A'>{}) /*| stdexec::split()*/;

    const bool add_B = true, add_C = true;

    using type_erased_sender_t = any_sender_of<stdexec::set_value_t()>;

    type_erased_sender_t for_B = add_B ? type_erased_sender_t(node_A | ::stdexec::then(Greetings<'B'>{})) : type_erased_sender_t(node_A);
    type_erased_sender_t for_C = add_C ? type_erased_sender_t(node_A | ::stdexec::then(Greetings<'C'>{})) : type_erased_sender_t(node_A);

    stdexec::sync_wait(stdexec::when_all(std::move(for_B), std::move(for_C)));
}
```

Here is an extract of the compiler output (`clang++` 18.1.3):
```bash
/workspaces/.../test_stdexec.cpp:146:42: error: no matching conversion for functional-style cast from '__call_result_t<__binder_back<then_t, Greetings<'B'>>, __sexpr<(lambda at /.../include/exec/../stdexec/__detail/__basic_sender.hpp:55:9){}, __anon> &>' (aka 'stdexec::__sexpr<stdexec::(anonymous namespace)::(lambda at /.../include/exec/../stdexec/__detail/__basic_sender.hpp:55:9){}>') to 'type_erased_sender_t' (aka 'any_sender<>')
  146 |     type_erased_sender_t for_B = add_B ? type_erased_sender_t(node_A | ::stdexec::then(Greetings<'B'>{})) : type_erased_sender_t(node_A);
```

Tagging @maikel because I think he introduced the "any" family.

**Comment by msimberg** [comment]
You're missing the stopped and error signatures from your any sender definition. If you look real hard in the error message (meaning you search for `_ERROR_`) you'll see that it says (among other things):
```
(aka '_ERROR_<stdexec::_MISSING_COMPLETION_SIGNAL_<stdexec::__rcvrs::set_stopped_t ()>, stdexec::_WITH_RECEIVER_<exec::__any::__rec::__ref<stdexec::completion_signatures<stdexec::__rcvrs::set_value_t ()>>>>')
```
On the right you have the signals that you are declaring (`set_value_t()`) and on the left it says that `set_stopped_t()` is missing (because split is cancelable). Similarly `set_error_t(exception_ptr const&)` is missing (because something can throw, and split sends const references to whatever it sends).

It's not obvious at all if you don't know to look for this, but once you know it's there, the error messages are actually really nice.

For reference, a compiling version of your code: https://godbolt.org/z/7v1xKdrb1.

**Comment by romintomasetti** [comment]
Indeed, this wasn't obvious if you don't know what you're looking for. Thanks for the pointers ! I guess the issue can be closed, though I would suggest that this could become a test or example somewhere in this repository :wink:
