### ISSUE TITLE
Which algorithms should be constrained with typed_sender?

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#187]
Some are currently constrained with `sender` but they clearly only worked with `typed_sender`s.

**Comment by griwes** [comment]
I've used typed_sender for all of those that obviously needed to store the value and error types somewhere, so needed to know what the storage type must be. It's probable that I've missed some that should be similarly constrained for other reasons.

**Comment by ericniebler** [comment]
Ah, I think what I'm seeing is that the pseudo-signatures of the algorithms in the "Design - user side" section don't reflect this. I'm putting together a PR that fixes how invocables are constrained in that section. I can make another pass through for the sender constraints.
