### ISSUE TITLE
Bifurcation of `when_(all|any)` seems likely to cause confusion in generic contexts.

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/stdexec#21]
> Therefore, we propose that when at least one of the sender arguments to the joining algorithms has an underlying scheduler, a user must also provide an explicit scheduler argument, which describes the scheduler that the returned sender will be bound to.

How do you know if your senders have an underlying scheduler in a generic context?

We don't have a separate concept for such senders (but see #19). Maybe we need one.

If I'm in a generic context, I could imagine it not being clear to me if I have senders that have underlying schedulers or not.

I wonder if perhaps these two overloads should have different names.

**Comment by LeeHowes** [comment]
I think we agreed today that when_all should not require that all senders not have completion schedulers, but that it simply be not propagate the completion_scheduler whatever they do.
