### ISSUE TITLE
recursion, inline completion, and stack usage

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#212]
@lewissbaker writes about `as_awaitable`:
> I am still a little concerned about the potential for unbounded recursion and stack-overflow if someone awaits a sender that completes synchronously in a loop with this formulation.
>
> Maybe this should conditionally schedule itself onto a trampoline_scheduler if the operation may potentially complete synchronously (e.g. if the `get_blocking()` CPO from P2257 was adopted and calling it returned something other than `asynchronous_completion_t`).

**Comment by kirkshoop** [comment]
tail_sender can solve this better than a trampoline.
