### ISSUE TITLE
Examples of chaining and transfer with I/O and complex object lifetimes

### ISSUE THREAD

**Issue by villevoutilainen** [NVIDIA/stdexec#25]
On various occasions, I have tried to understand how P0443 schedulers and senders provide something roughly along the lines of the following:

1) launch an asynchronous operation that opens a file (well, socket), and produces a file descriptor
2) somehow "pipe" that to another asynchronous operation that reads data from the file, and produces that data to its consumers

The current approach looks like I might more easily wrap my head around how to do that, but I may be wrong. With P0443, it was all too easy to think "oh, I need a receiver that also acts as a sender, so I'll receive the descriptor from one sender and then act as a sender that initiates the data read". In this model, I might envision starting work on a scheduler to open the file, and then transfer that to another scheduler (most likely actually the _same_ scheduler) and then piping the descriptor into the new-work, which would then produce different values/results.

But I have no idea whether that's the correct train of thought. Can we have an example of how to do the example described above?

There are different possible examples here that would be quite helpful. Suppose I have async work that sends a HTTP HEAD request to a web server, and produces an object of a class type describing the response of the request, and then I want to "pipe" that into subsequent work that examines that response object, and if successful, initiates more work to actually HTTP GET some data out of it, and then pipes that into subsequent work that actually reads the response body of the GET request.

And namely

1. Examples where all this is done with different (C++) types of data produced by the different pieces of work
2. Also examples where some of that data is shared; either by refcounted objects, or by Out-of-Band shared data that the different stages of work know about. Fine, chances are that they know about it by virtue of references or reference-semantic objects referring to it being passed through the "pipelines", but still.

**Comment by brycelelbach** [comment]
Can you take a look at the async read example in the paper and let us know if that's the sort of thing you're looking for, or if you want to see something more advanced?
