### ISSUE TITLE
What forward progress guarantee should the run_loop provide?

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#281]
It presently doesn't specify a forward progress guarantee.

**Comment by lewissbaker** [comment]
It would presumably only be able to provide either parallel progress (if the thread calling `run()` had a concurrent forward progress guarantee) or weak-parallel progress (if the thread calling `run()` has only a weak forward progress guarantee. 

But we may also want to take into account the forward progress requirements of the schedule operation itself.
e.g. the reference implementation of `run_loop`'s schedule operation acquires a mutex lock to insert the item in the queue. This means that it would generally only be safe to call `start()` on the schedule operation from a thread with a strong forward progress guarantee.
