### ISSUE TITLE
receiver<T, E> should also check for std::exception_ptr

### ISSUE THREAD

**Issue by lucteo** [NVIDIA/stdexec#285]
P2300R2 `receiver` concept has the following `requires` clause:
```{ execution::set_error(std::move(t), (E&&) e) } noexcept;```

On the other hand, the paper refers to `receiver` concept in multiple context without specifying the error type (i.e., definition of `receiver_of`, `sender_to`,  etc.) More importantly, the definition of `connect()` requires for the `R` type to be a `receiver` (without the possibility of inferring the error type).

This means, that even if a type `R` models `receiver<E>` (with `E` != `exception_ptr`), it will be used by the framework as a simple `receiver`. If the the type `R` doesn't properly allow calls to `set_error(R, exception_ptr)`, it cannot be used with the rest of the primitives.

Thus, the best way to ensure that a receiver type is properly specified is to add another `requires` clause:
```{ execution::set_error(std::move(t), exception_ptr{}) } noexcept;```
ensuring that the receiver also support exceptions.

**Comment by ericniebler** [comment]
the design has changed here; receivers are no longer required to handle `exception_ptr`
