### ISSUE TITLE
The value of `error_types` for `just_error()`

### ISSUE THREAD

**Issue by lucteo** [NVIDIA/stdexec#286]
P2300R2 exposes in the possible implementation of `just_error()` the following definition for `error_types`:
```{C++}
  template<template<class...> class Variant>
  using error_types = Variant<T, exception_ptr>;
```

What happens if one calls `just_error<std::exception_ptr>(std::current_exception())`?
Would the `error_types` value be `Variant<exception_ptr, exception_ptr>` or just `Variant<exception_ptr>` ?

I would argue that it's better to have `exception_ptr` occur only once. But, I think, the paper should clarify this.

(On a side topic: I assume that cases in which we have `Variant<T, T>` are just bad design, and the implementor of these senders are responsible for the poor design; probably it doesn't make sense for the paper to clarify this)

**Comment by ericniebler** [comment]
no longer an issue
