### ISSUE TITLE
Clarify that scheduler returned by get_scheduler on receiver is only valid until the operation completes

### ISSUE THREAD

**Issue by lewissbaker** [NVIDIA/stdexec#295]
Similar to the wording in the `get_stop_token()` CPO, which only guarantees that the token returned is valid until the operation completes, we should do the same for the `get_scheduler()` CPO.

We should be careful to clarify what operations are valid after calling set_xxx on the receiver.
e.g. is it valid to call:
* the destructor of the scheduler after `set_xxx` (could some schedulers be reference-counting in the destructor?)
* the move constructor?
* the `schedule()` CPO (but just not connect/start it)

Another possibility is to tie the end-of-validity of the scheduler to the destructor of the receiver (or move-constructed copy of the receiver).

**Comment by LeeHowes** [comment]
We might want to use the more general wording if get_scheduler is a broader query than just on the receiver.
