### ISSUE TITLE
Over-strict(?) requirements on typed_senders

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#302]
[execution.senders.traits]/6 reads:

> [...] If such sender `S` odr-uses `execution::set_value(r, args...)` for some receiver `r`, where `decltype(args)...` is not one of the type packs `Args0...` through `ArgsN...`, the program is ill-formed with no diagnostic required.

I think requiring _exact_ type matching here seems over-strict to me. If a sender reports that it sends an `int` but actually sends an `int&` or `const int&`, IFNDR seems a bit harsh.

I'm also curious if we really mean `decltype(args)` here instead of `decltype((args))`. Only questions, no answers at this point.

**Comment by lewissbaker** [comment]
I think that we'd have to require that the value categories match.

If a sender says it sends an `int&` in its value_types then I might create a type-erased receiver that has only a `set_value(my_receiver&, int&)` overload. If you send a `const int&` or an `int` then `set_value()` is not going to be invocable.

I think that if a sender reports it will send the value-pack `Ts...` then it should require that `set_value(r, std::declval<Ts>()...)` is well-formed for the receiver to be a compatible receiver.
There is no guarantee that the receiver's `set_value()` will be invocable if you pass a different argument pack type.
