### ISSUE TITLE
Add utility for emplace-constructing a non-movable type

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#318]
Add this, per request from @villevoutilainen :

```c++
template <invocable _Fun>
struct some_damn_name {
  _Fun __fun; // exposition only
  invoke_result_t<_Fun> operator()() && noexcept(is_nothrow_invocable_v<_Fun>) {
    return move(__fun)();
  }
};
template <invocable _Fun>
some_damn_name(_Fun) -> some_damn_name<_Fun>;
```

This can be used to emplace-construct non-movable types (like, say, an operation state) into (say) an `optional`.

If we name things by what they _do_, this would be something like `convertible_to_result_of` (yuk!). IF we name it by what it's _for_, it would be something like `elide_copy_from`.

I kinda like `elide_copy_from`, but others are likely to have different opinions.

**Comment by lewissbaker** [comment]
I think that you want to define `some_damn_name::operator invoke_result_t<_Fun>()` rather than `some_damn_name::operator ()`.
The latter is just wrapping the callable into another callable rather than wrapping it into something that is convertible to the result type.
