### ISSUE TITLE
start_detached should be constrained to only accept senders of void

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#325]
Accepting senders that send values and then silently dropping the values on the floor seems ... odd? Like it could hide bugs? My gut tells me we should constrain this.

Thoughts welcome.

**Comment by lewissbaker** [comment]
Yes, that was my gut feeling also.
Although it may then necessitate the addition of another helper algorithm `discard_value(s)` that explicitly discards any value from `set_value()` and calls `set_value()` with no args.
e.g. `auto discard_value(auto&& s) { return then(static_cast<decltype(s)>(s), [](auto&&...) noexcept {}); }`

Although there is the counter example that we have `std::thread` able to accept non-void-returning lambda which it just silently discards the result of...

**Comment by ericniebler** [comment]
> Although there is the counter example that we have `std::thread` able to accept non-void-returning lambda which it just silently discards the result of...

It wouldn't be the first time LEWG decided to not repeat the mistakes of `std::thread`.

**Comment by ericniebler** [comment]
fixed
