### ISSUE TITLE
Complete the reference implementation of P2300

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#336]
Currently the missing pieces are:

- [x] `ensure_started`
- [x] `get_forward_progress_quarantee`
- [x] `execute_may_block_caller`
- [x] `upon_error`
- [x] `upon_stopped`
- [x] `bulk`
- [x] `split`

**Comment by lewissbaker** [comment]
Were we still going to remove `ensure_started` and `split` in favour of `async_scope`?
Is it still worth implementing these algorithms if that is the case?

**Comment by LeeHowes** [comment]
I think we also need:
 * The blocking query (#225) which is fundamental to make things like async_scope safe.
 *  with_query_value so we can inject allocator, scheduler delegee scheduler #314 

I mention them here so we don't forget them. We need them in the paper as well though.

**Comment by ccotter** [comment]
Is there any interest in having someone provide `ensure_started`? I'd be interested in providing one

**Comment by ericniebler** [comment]
Cool. An NVIDIA intern has implemented it and should be submitting a pull request soon. We'll need plenty of eyes on it since it's a tricky algorithm, and it may need work. Perhaps you could help with that.

There's no shortage of other issues, too.

**Comment by ccotter** [comment]
Sounds good, I'll keep my eye out for that PR. I'll keep lurking around the set of open issues. If you have any "high priority" open issues that you'd like to see done sooner rather than later, let me know too.
