### ISSUE TITLE
Sudoku example note about TBB implementation leaking is out of date

### ISSUE THREAD

**Issue by lewissbaker** [NVIDIA/stdexec#343]
> In addition to eliminating the need for reference counting, the use of structured concurrency makes it easy to ensure that resources are cleaned up on all code paths. In contrast, the TBB example that inspired this one leaks memory.

The TBB issue referenced here has been marked as resolved: https://github.com/oneapi-src/oneTBB/issues/568

Should we update this note to remove the reference to the TBB example leaking?

**Comment by ericniebler** [comment]
moot. we're at the LWG wording review stage.
