### ISSUE TITLE
[execution.schedulers.queries.execute_may_block_caller] Missing design rationale

### ISSUE THREAD

**Issue by lewissbaker** [NVIDIA/stdexec#348]
The `this_thread::execute_may_block_caller()` CPO is added by P2300 but there is no design discussion of this customisation point that motivates its addition, explains its purpose or how it is intended to be used.

Can we add some discussion for this method?

**Comment by romintomasetti** [comment]
@ericniebler There are still few occurences of `execute_may_block_caller` here and there (e5dbe49a5257d29adee456f9f653acb00df634f5).
