### ISSUE TITLE
`receiver_adaptor`'s helper exposition only concepts `has-set-value` etc potentially trying to access private members

### ISSUE THREAD

**Issue by huixie90** [NVIDIA/stdexec#352]
In 9.9.1 number 5, there is an example
```
template <execution::receiver_of<int> R>
  class my_receiver : execution::receiver_adaptor<my_receiver<R>, R> {
    friend execution::receiver_adaptor<my_receiver, R>;
    void set_value() && noexcept {
      execution::set_value(std::move(*this).base(), 42);
    }
   public:
    using execution::receiver_adaptor<my_receiver, R>::receiver_adaptor;
  };
```
note that the member function `set_value` is private and give access to receiver_adaptor via friendship.

but on number 2, the exposition only concept is defined as
```
template <class Receiver, class... As>
  concept has-set-value =
    requires(Receiver&& r, As&&... as) {
      static_cast<Receiver&&>(r).set_value(static_cast<As&&>(as...));
    };
```
It is trying to test the existence of the member function `set_value`, but in this case, as it is private, so it will return false

**Comment by ericniebler** [comment]
It appears that you are correct, despite the fact that both clang and gcc accept the code without complaint.

**Comment by ericniebler** [comment]
fixed
