### ISSUE TITLE
how does the initialisation of some sender adaptor closure objects work in the example code?

### ISSUE THREAD

**Issue by huixie90** [NVIDIA/stdexec#360]
In the example implementation execution.hpp line 1171, we have
```
 template <class _T0, class _T1>
    struct __compose : sender_adaptor_closure<__compose<_T0, _T1>> {
      [[no_unique_address]] _T0 __t0_;
      [[no_unique_address]] _T1 __t1_;
```

and then on line 1195 we have
```
  return {(_T0&&) __t0, (_T1&&) __t1};
```
I'd expect 3 arguments to init the aggregate (the first one should init the base class). but there is no `{}` to init the base class `sender_adaptor_closure`. Is there anything I missed?

**Comment by ericniebler** [comment]
fixed
