### ISSUE TITLE
wording of the `then` sender adaptor

### ISSUE THREAD

**Issue by huixie90** [NVIDIA/stdexec#361]
several minor points of the wording about 

> Otherwise, the expression execution::then(s, f) is expression-equivalent to:
`tag_invoke(execution::then, get_completion_scheduler<set_value_t>(s), s, f)`, if that expression is valid and its type satisfies `execution::sender`.
Otherwise, ...

1. perhaps consider adding that the subexpression `s` is only evaluated once (since it appears twice in the full expression)
2. according to the spec, if the result of the `tag_invoke` doesn't satisfy `sender`, it should go to "Otherwise" clause (fallbacks). but in the example implementation
```
template <sender _Sender, __invocable_with_values_from<_Sender> _Fun>
        requires __tag_invocable_with_completion_scheduler<then_t, set_value_t, _Sender, _Fun>
      sender auto operator()(_Sender&& __sndr, _Fun __fun) const
```
The overload is still selected but errors on the return type not satisfying the `sender` concept

We need to either fix the implementation to match the spec or modify the spec to match the implementation. I personally in favour of erroring out.

3. `void` handling in 
> When execution::set_value(r, args...) is called, calls invoke(f, args...) and passes the result v to execution::set_value(out_r, v)
 
I believe this issue is captured somewhere else.

**Comment by ericniebler** [comment]
no longer applies
