### ISSUE TITLE
in_place_stop_source ::stop_possible has inconsistent semantics

### ISSUE THREAD

**Issue by hkaiser** [NVIDIA/stdexec#416]
The semantics of `in_place_stop_source::stop_possible` differ from those of `std::stop_source::stop_possible`.

`in_place_stop_source::stop_possible`:

    Returns: true if the stop state inside *this has not yet received a stop request; otherwise, false.

`std::stop_source::stop_possible` (see: http://eel.is/c++draft/thread.stoptoken#stopsource.mem-2):

     Returns: true if *this has ownership of a stop state; otherwise, false. 

This leads to different return values after `request_stop()` was called.

**Comment by ericniebler** [comment]
The reason for the difference is that `in_place_stop_source` maintains all its state internally. It doesn't dynamically allocate a stop state, so there isn't a sense in which it could "own" or "not own" a stop state.

> This leads to different return values after `request_stop()` was called.

This isn't clear to me. How?

**Comment by hkaiser** [comment]
> The reason for the difference is that `in_place_stop_source` maintains all its state internally. It doesn't dynamically allocate a stop state, so there isn't a sense in which it could "own" or "not own" a stop state.

I understand. This part is not the issue, rather the fact that `stop_token` still returns `true` from `stop_possible()` even if `request_stop()` was called.

> > This leads to different return values after `request_stop()` was called.
> 
> This isn't clear to me. How?

Our unit tests for `stop_token` report problems when used for `in_place_stop_token`, as said the return value from `stop_possible()` is different for both (if implemented as specified).

**Comment by ericniebler** [comment]
I'll need @griwes and @lewissbaker to weigh in here. Lewis designed the cancellation system. I strongly suspect this is by design, but I'll let Lewis and Michal speak.

**Comment by lewissbaker** [comment]
The semantics for in_place_stop_token::stop_possible() should be to return true if it is not a null stop token (ie was obtained from in_place_stop_source::get_token()), otherwise false if it is a null stop token (ie was default constructed)
