### ISSUE TITLE
in_place_stop_token::stop_possible has inconsistent semantics

### ISSUE THREAD

**Issue by hkaiser** [NVIDIA/stdexec#417]
The semantics of `in_place_stop_token::stop_possible` differ from those of `std::stop_token::stop_possible`.

`in_place_stop_token::stop_possible`:

    Returns: source_ != nullptr && source_->stop_possible().

`std::stop_token::stop_possible` (see: http://eel.is/c++draft/thread.stoptoken#stoptoken.mem-2):

     Returns: false if:
     - *this does not have ownership of a stop state, or
     - a stop request was not made and there are no associated stop_­source objects; otherwise, true.

This leads to different return values after `request_stop()` was called on the associated source object.

**Comment by ericniebler** [comment]
> This leads to different return values after `request_stop()` was called on the associated source object.

How so?

**Comment by hkaiser** [comment]
> > This leads to different return values after `request_stop()` was called on the associated source object.
> 
> How so?

As mentioned in https://github.com/brycelelbach/wg21_p2300_std_execution/issues/416, after `request_stop()` was called, `in_place_stop_token::stop_possible()` always returns `false`, while `stop_token::stop_possible()` may still return `true`.
