### ISSUE TITLE
`get_completion_scheduler` is not a forwarding sender query?

### ISSUE THREAD

**Issue by msimberg** [NVIDIA/stdexec#419]
In my understanding it should be one, but I don't see any wording specifying that it is a forwarding query. Is there some blanket wording that makes it a forwarding query that I've missed? The default for `forwarding_scheduler_query` is `false`.

**Comment by ericniebler** [comment]
It should not be a forwarding sender query. It wouldn't be safe to inherit completion schedulers by default because so many senders change where they will complete.

**Comment by msimberg** [comment]
Fair enough, that makes sense. Thanks! My follow-up question is then: are there really no adapters (of the ones defined in P2300, not in general) other than `transfer`, `schedule_from`, `when_all`, and `transfer_when_all` that should advertize completion schedulers in the uncustomized implementations? Is even `get_completion_scheduler<set_value_t>` for `then` unsafe to forward in the default implementation? Sorry if I'm missing something obvious.

**Comment by griwes** [comment]
Hang on. The intent of the initial design was that sender adaptors propagate this query unless otherwise specified, and that's what the wording I originally wrote for sender adaptors did. If this isn't forwarded, then the entire customization scheme of only specializing *some* of the algorithms entirely falls apart.

**Comment by lewissbaker** [comment]
This presumably only works for senders that adapt exactly one input sender and only where the operation completes on the same execution context as the one that you are composing. i.e. if you are `then()`-like.

An algorithm that composes multiple input senders would need to decide which of the input senders to forward queries to.
e.g. a `when_all(a, b)` algorithm might complete on completion context of either `a` or `b`.

I am skeptical that the goal of only trying to customise _some_ algorithms while still dispatching to custom implementations is achievable.

**Comment by griwes** [comment]
We've explicitly specified when_all to not forward the query. I'm not sure what your concern here is.

**Comment by lewissbaker** [comment]
Maybe you mean that _for the default implementation of sender adaptors in the standard library_ the returned senders propagate it? Rather than a requirement for all sender adaptors that might ever be created (which is how I originally read your comment)?
