### ISSUE TITLE
Remove default implementation of `bulk`

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#428]
`bulk` should require customization. Per LEWG request.

**Comment by lewissbaker** [comment]
This seems user-hostile for people wanting to use `bulk` with a generic scheduler.

It's effectively necessitating an extra `bulk_scheduler` concept that algorithms would constrain themselves with if they ever wanted to use `bulk`.

Are there minutes somewhere that record what the concerns are with a default `bulk` that just used `schedule()` and a for-loop?

**Comment by griwes** [comment]
There are minutes, here: https://wiki.edg.com/bin/view/Wg21telecons2021/Executors-2021-10-19-Part-1.

**Comment by ericniebler** [comment]
LEWG backed down. `bulk` lives on.
