### ISSUE TITLE
specification of default implementations of sender algorithms in the standard library need to specify when they decay copy values and errors.

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#443]
See `when_all`, for example.

**Comment by lewissbaker** [comment]
Why is this needed?

**Comment by ericniebler** [comment]
(a) it's observable, (b) it effects whether a sender is no-fail or not (copies/moved can throw)

**Comment by lewissbaker** [comment]
The `when_all` sender would presumably conditionally report that it can complete with an exception if decay-copying any of the value-results of any of the input senders is `noexcept(false)`. I don't see why we would need to report that the operation might copy the values as a separate thing.

That a sender copies the value is presumably just part of the specification of that sender/algorithm.
Why would a user of that sender need to know whether it copies result values from its child senders?

**Comment by ericniebler** [comment]
> That a sender copies the value is presumably just part of the specification of that sender/algorithm.

I thought the specification was what we were talking about. What I'm saying is that the specification for `when_all` should say that it necessarily needs to temporarily store values/errors in the operation state. What are you saying?

**Comment by lewissbaker** [comment]
Sorry, for some reason I thought you were suggesting that we add a metafunction/query for a sender (like a completion_signatures query) that would allow a program to query at compile time whether a sender will copy the result of its child.

**Comment by ericniebler** [comment]
OK, that's reasonable confusion. I've updated the title of the issue.
