### ISSUE TITLE
Should we require at least one completion signature for a type to be a sender?

### ISSUE THREAD

**Issue by anthonywilliams** [NVIDIA/stdexec#448]
Is this type a sender?

~~~
struct S {
  using completion_signatures = execution::completion_signatures<>;
};
~~~

The `completion_signatures` type is an instance of `execution::completion_signatures`, and it's move-constructible, so it satisfies the `sender` concept from P2300R5. However, it feels wrong to say it is a sender, as it never sends anything.

Can we require that a valid `sender` has at least one completion signature?

**Comment by ericniebler** [comment]
i don't think we are going to be making changes in this area. closing.
