### ISSUE TITLE
get_env should require a non-`void` type for the environment type

### ISSUE THREAD

**Issue by anthonywilliams** [NVIDIA/stdexec#449]
As it stands, the following meets the `receiver` concept, since it provides a `get_env` customization, and the result of `tag_invoke(execution::get_env,R{})` is not `execution::no_env`

~~~
struct R {
  friend void tag_invoke(execution::get_env_t,R) noexcept {}
};
~~~

However, it cannot connect, since `get_completion_signatures_of_t` requires calling `get_completion_signatures(S{},E{})` which fails if `E` is `void`.

In addition to mandating that the return type of `tag_invoke(execution::get_env,R{})` is not `no_env`, can we mandate that it is not `void`?

**Comment by ericniebler** [comment]
`get_env` is now mandated to return a type that satisfies `queryable`, which requires `destructible`. `void` is not `destructible`.
