### ISSUE TITLE
10.8.1.1. execution::completion_signatures_of_t paragraph 4 issues

### ISSUE THREAD

**Issue by huixie90** [NVIDIA/stdexec#457]
> Mandates: `is-instance-of<Sigs, completion_signatures>` or `is-instance-of<Sigs, dependent_completion_signatures>`, where Sigs names the type `tag_invoke_result_t<get_completion_signatures_t, S, E>`.

Since `dependent_completion_signatures` has "arguments are not associated entities", its typical implementations would be a type alias to some inner struct. `is-instance-of` would always fail because the impl struct would not be a template (as an ADL wall).

**Comment by ericniebler** [comment]
This is already fixed in main. `completion_signatures` is an ordinary class template now; it doesn't hide the associated entities of the template arguments.

**Comment by huixie90** [comment]
@ericniebler  but `dependent_completion_signatures` still has  "arguments are not associated entities"

**Comment by ericniebler** [comment]
`dependent_completion_signatures` is no longer a thing
