### ISSUE TITLE
Add support for custom allocators to split() algorithm

### ISSUE THREAD

**Issue by lewissbaker** [NVIDIA/stdexec#463]
The `split()` algorithm typically needs to heap allocate some storage that is shared between the various split-sender objects.

The current reference implementation just calls global operator new/delete to allocate this storage.
We should extend this to support the user providing a custom allocator for this.

I see two main options for this:
* Add an extra overload that allows someone to optionally explicitly pass an allocator as a second argument to `split()`.
  e.g. `split(some_sender, my_allocator)`
* Have `split()` obtain the allocator to use by calling `get_allocator()` on the input sender.

I can also imagine both of these options being made available.
e.g. if you pass an explicit allocator then use that, otherwise use the allocator from the input sender, otherwise use std::allocator.

**Comment by ericniebler** [comment]
moved to cplusplus/sender-receiver#46
