### ISSUE TITLE
Extra layer of `tuple` in `sync_wait_with_variant`

### ISSUE THREAD

**Issue by Chlorie** [NVIDIA/stdexec#468]
The specification for `sync_wait`'s default behavior is just `sync_wait(into_variant(sndr))`, so consider a sender that sends `(int, int), (float)`, `into_variant` makes it a sender sending `variant<tuple<int>, tuple<float>>`, and thus `sync_wait` of it should return `optional<tuple<variant<tuple<int, int>, tuple<float>>>>`. Since `into_variant` would only send a single set of values, isn't the outer layer of `tuple` unnecessary? `optional<variant<tuple<int, int>, tuple<float>>>` is preferred in this case.

**Comment by ccotter** [comment]
Related - section 5.8 does appear to have a typo, or at least an inconsistency. `sync_wait_with_variant` is stated as returning result without the extra `tuple`:

```
auto sync_wait_with_variant(
    execution::sender auto sender
) -> std::optional<std::variant<
        std::tuple<values0-sent-by(sender)>,
        std::tuple<values1-sent-by(sender)>,
        ...,
        std::tuple<valuesn-sent-by(sender)>
    >>;
```

Section 10.8.6.2 does define the default implementation as equivalent to `sync_wait(into_variant(sndr))`, which conflicts with the above. At the very least, we should update section 5.8 to match the actual value types of `into_variant(sndr)`.

**Comment by ericniebler** [comment]
This issue is moved to cplusplus/sender-receiver#22
