### ISSUE TITLE
`let_xxx` algorithms always specify `set_error_t(exception_ptr)` in the completion signatures

### ISSUE THREAD

**Issue by anthonywilliams** [NVIDIA/stdexec#472]
The `let_xxx` algorithms always specify `set_error_t(exception_ptr)` in the completion signatures, even if no exceptions can be thrown.

e.g. if I provide a `sender`, such that `execution::connect(my_sender,r)` is `noexcept`, and the arguments supplied to `set_value` by my sender are nothrow-move-constructible (e.g. `int`), and my sender never completes with `set_error`, then `let_value(my_sender,[](auto ...) noexcept{ return another_noexcept_sender{}; })` should never complete with `set_error` either, since none of the constituent parts throw.

Thus, we need another `potentially-throwing` determination here, that detects if any of:

* invoking `execution::connect(s,r)` can throw
* storing `args'...` in `op_state` can throw (i.e. any of the types in `Args` are *not* `nothrow_move_constructible`) for any of the possible sets of `Args` for the completion of the source sender `s`.
* invoking `connect(f(args'...),out_r)` can throw

and only includes the `set_error_t(exception_ptr)` in the completion signature if things are potentially throwing.

**Comment by Chlorie** [comment]
This might be impossible to implement under the current spec since we only get the environment type but not the receiver type in `get_completion_signatures`, which means that we cannot decide whether the connection would fail.

**Comment by anthonywilliams** [comment]
In order to implement this, then you connect the original sender with a proxy receiver. The proxy receiver then forwards to the final receiver. This way the type of the proxy receiver is known when determining whether or not the internal `connect` throws. I have implemented this.

**Comment by Chlorie** [comment]
> In order to implement this, then you connect the original sender with a proxy receiver. The proxy receiver then forwards to the final receiver. This way the type of the proxy receiver is known when determining whether or not the internal `connect` throws. I have implemented this.

That is really a neat way that I haven't thought of to tackle the problem. Thanks for the inspiration!

**Comment by ericniebler** [comment]
@anthonywilliams Your proxy receiver suggestion requires something like virtual dispatch if I understand correctly. You want to test the noexcept-ness of `connect` before the actual receiver type is known. The indirect function call will lead to worse runtime perf.

Do I have that right? In your opinion, this trade-off is worth it?

**Comment by anthonywilliams** [comment]
Yes, it requires virtual dispatch, and yes it's a trade-off. If the cost isn't too high, I think it is worth it for the static properties that result. Being able to guarantee that there are no exceptions thrown is quite a nice property, and make it play better with freestanding environments.

However, I have not profiled it, or done this with real code and data, so I cannot tell you how the trade-off fares in practice.

**Comment by ericniebler** [comment]
It occurs to me that an implementation already has the freedom to provide an implementation that uses virtual dispatch to eliminate the possibility of a `exception_ptr` completion. I added implementor freedom to drop the `set_error_t(exception_ptr)` completion from any sender adaptor if the implementation is known statically to never call `set_error` with an `exception_ptr` ([[exec.adapt.general]/p7](https://brycelelbach.github.io/wg21_p2300_execution/execution.html#spec-execution.senders.adapt.general)).

This implementor freedom is good enough for me. @anthonywilliams ?
