### ISSUE TITLE
{#design-adapter-transfer}: Rename `transfer`

### ISSUE THREAD

**Issue by LeeHowes** [NVIDIA/stdexec#5]
This is like via but returns a sender that returns sch for get_completion_scheduler.

It can also optimise internally if it knows what scheduler the incoming sender completes on.

Interestingly, though, we could build on issue 4 here: if the incoming sender is strictly lazy, the returned sender here might also be strictly lazy, but we always provide a completion scheduler here because that is the definition of a transition.

This would mean we don't necessarily accidentally introduce eagerness, but we do always inject the information we want.

**Comment by LeeHowes** [comment]
@griwes do you mean consequences such as propagating the scheduler and causing subsequent work to (potentially, in an eager world) also run on the scheduler?

`schedule_subsequent` or something like that might work - but lazy implementations of later algorithms might still not run on that scheduler so it's not entirely true.

**Comment by griwes** [comment]
I'd like to avoid using a name that starts with `schedule`; I think these should be (implicitly or explicitly) reserved for operations that accept a *scheduler* as a first argument (see also: `schedule_from`).

>  Are you wanting to guarantee more than what it says on the tin for `get_completion_scheduler()`?

I'd like to have a name that speaks to *what* this algorithm is trying to accomplish, as opposed to one that speaks to *how* it is done.

**Comment by brycelelbach** [comment]
I don't love `reschedule` myself - it sounds like it takes a running thing and moves it to a new execution context.

**Comment by brycelelbach** [comment]
We talked about this on 2021-06-30. We don't have any better ideas than `transfer`, and @LeeHowes feels that its okay at least for the time being.
