### ISSUE TITLE
generalize the `read` sender factory

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#538]
`read(cpo)` is a sender that fetches the value of the query `cpo` from the receiver's environment and sends it through the value channel. Here are two ideas for making it more general:

- [ ] Support reading multiple CPOs at a time; _e.g._, `read(cpo1, cpo2, cpo3)` would read three values from the receiver and send them all through the value channel.
- [ ] Support a way to specify a default value to use if the receiver's environment doesn't implement the CPO; _e.g._, `read(with(cpo, value))`.

See also #539, #540

**Comment by miscco** [comment]
That feels like a monadic interface. would `value` and `value_or` fit here?

**Comment by ericniebler** [comment]
Maybe :

```c++
when_all(value(cpo1), value_or(cpo2, default))
```

?
