### ISSUE TITLE
Providing environment information to algorithms that eagerly `connect` senders

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#554]
`ensure_started` and `start_detached` need an allocator and possibly more besides (stop token?). `split` as currently specified needs an allocator. `sync_wait[_with_variant]` could use a stop token. In the `async_scope` paper, `spawn` and `spawn_future` also need allocators.

If we end up proposing scoped, `connect`-based customization (#518), these algorithms will probably need a domain tag for the purpose of finding customizations. They should also optionally accept a scheduler representing the calling execution context, so that a scoped variant of `on` can complete on the correct scheduler.

We have a couple of options for providing this information:

1. Use sender adaptors to decorate the input sender with the required environment.
2. Pass the environment as a separate, optional argument along with the sender.

The appeal of (1) is that the shape of the algorithms doesn't need to change. The downside is that these adapted senders turn into environment providers, something they are not currently (and arguably shouldn't be). If that environment information is intended for the receiver (information flowing inward, from outer adaptors to more nested ones), then turning those senders into environment providers means the information is also flowing in the other direction, from the outer adaptors to the algorithm operating on them. That seems odd.

OTOH, if this information is _not_ intended for the receiver and is _only_ intended to be consumed by the algorithm, when why is it not passed as an argument to the algorithm instead? Putting it on the sender seems like a conflation of responsibilities.

My preference is for option (2).

**Comment by griwes** [comment]
+1 for option 2.
