### ISSUE TITLE
Rethink cancellation

### ISSUE THREAD

**Issue by jamboree** [NVIDIA/stdexec#573]
In the current design, cancellation support for an operation is externalized and somewhat convoluted, you have to `get_stop_token` from the receiver, check if `stop_requested`, register a callback during `start` and unregister it upon complete. Things could be made simpler if cancellation is intrinsic to the operation-state. That is, in addition to a `start` function, an operation-state should also has a `drop`/`stop` function.

The rules:
* `drop` can only be called after `start`, potentailly from another thread.
* `drop` can be called 0 or 1 time.
* `drop` after completion is permitted and has no effect (still shouldn't be called more than once).
* `drop` doesn't necessarily result in `set_stopped` being called; `set_stopped`  being called doesn't necessarily caused by `drop`.

Also, it should be made clear that *receiver contract* is only fulfilled after `start`. Simply `connect` and destruct the operation-state should not invoke any channel of the receiver.

**Comment by maikel** [comment]
> This would be problematic since typically the completion functions free resources, including the operation state itself.

In general, this is indeed a problem. But there are situations where a droppable op state concept might be sensible, such as in a repeat algorithm. 

I have implemented a test where the caller of `drop` controls the lifetime of the droppable operation. This happens in sequence senders quite often where a sequence manages one are more op states for it's elements.

**Comment by jamboree** [comment]
> > drop after completion is permitted and has no effect (still shouldn't be called more than once).
> 
> This would be problematic since typically the completion functions free resources, including the operation state itself.

The point is that there's an eventual owner of the operation state, if the caller is able to call `drop` on the operation state, the  operation state must still be alive, and it doesn't matter the operation is completed or not.
