### ISSUE TITLE
Should `connect` take receivers by value?

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#583]
In practice, the receivers passed to `connect` are almost always prvalues. The `connect` CPO accepts the receivers by forwarding reference, forcing the materialization of a temporary. Given C++17's deferred materialization of temporaries, if the `connect` CPO took the receiver by value, that temporary wouldn't actually be materialized.

However, when the `connect` CPO forwards the receiver to `tag_invoke`, I _think_ that forces the materialization of the temporary, so there isn't a way to get the receiver where it needs to be without some moves.

:thinking:

**Comment by lewissbaker** [comment]
If we manage to get language CPOs then the forced materialisation of temporaries currently needed by tag_invoke-based dispatch can be eliminated.

I think passing receivers by-value does simplify the implementation of `connect()` customisations, though, as you don't have to decay-copy and perfectly-forward. You can just `std::move()` the receiver. Most of the time the receiver is a single pointer to the operation state anyway.
