### ISSUE TITLE
Either clarify the term "execution agent" or remove it from the specification

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#588]
This came up in discussion of the valid implementations of `bulk`. The design section of P2300 talks of `bulk` launching "`space`" execution agents. It isn't clear if a simple loop iteration (say, like the one the default sequential `bulk` implementation would use) qualifies as an execution agent.

The term agent appears many times both in the Design section and in the Specification. These all need to be examined and the intent clarified. This might involve striking the term "agent" entirely.

**Comment by griwes** [comment]
I would prefer not to deal with this editorially, and rather ask for explicit SG1 direction on what they want to happen here.

**Comment by ericniebler** [comment]
That is probably wise.
