### ISSUE TITLE
Compiler Explorer integration

### ISSUE THREAD

**Issue by ccotter** [NVIDIA/stdexec#612]
As P2300 gets more traction, Compiler Explorer support would go a long way. Sharing code snippets, testing out sample code, and importantly, spreading knowledge and awareness along the way.

What would we need to make this happen? Happy to help.

**Comment by ccotter** [comment]
@ericniebler - what do you think? I tested this with a local instance of compiler explorer and it looks good. If you're on board, I can work with the compiler explorer folks to make this happen.

**Comment by jrhemstad** [comment]
Already under way :) 

https://github.com/compiler-explorer/compiler-explorer/pull/4201

**Comment by maikel** [comment]
This can be closed, correct? AFAIK, there is a nightly mirror for CE.

**Comment by jrhemstad** [comment]
Indeed, this is already done.
