### ISSUE TITLE
Investigate why this change was necessary to satisfy clangd

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#688]
https://github.com/NVIDIA/stdexec/pull/684/files#r1024429915

This change suggests to me that there is something slightly amiss about the CUDA stream `let` senders.

**Comment by senior-zero** [comment]
let senders will cause sender construction on GPU. We do not annotate sender constructors explicitly with `__host__ __device__`. Unlike nvc++, clang doesn't support implicit annotations.
