### ISSUE TITLE
publicly expose "sender_adaptor_closure" as a concept

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#710]
and "sender_adaptor_closure_for" too.

**Comment by jefflarkin** [comment]
Hopefully we can come up with a more succinct name. :)

**Comment by ericniebler** [comment]
`sender_closure` would suit me just fine. Stepanov calls a function `T->T` a "transform" so I would also be ok with `sender_transform` (although I expect we'll have a `transform` algorithm someday that operates on async streams).
