### ISSUE TITLE
Lifetime guarantees of a sender's queryable environment

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#764]
It's clear that a receiver's environment should have reference semantics. But is that also true for a sender's? Might it not be sometimes desirable to copy a sender's environment into the operation state, letting go of the sender itself?

If so, a sender's environment needs value semantics, or else a way to "deep copy" the environment. The latter could be as simple as a way of enumerating the queries that an environment supports, which could be useful elsewhere as well; _e.g._, it could be useful in a facility that generates type-erased wrappers for queryables.

**Comment by Runner-2019** [comment]
mark
