### ISSUE TITLE
Implement `on_coroutine_succeeded()` and `on_coroutine_failed()`

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#767]
In addition to `at_coroutine_exit()`, the `task<>` type can support `on_coroutine_succeeded()` and `on_coroutine_failed()`. Those will register a (possibly asynchronous) cleanup action that knows whether `unhandled_exception()` was called on the promise or not.

**Comment by maikel** [comment]
I wonder if there is a particular reason to ignore the third channel, i.e. `on_coroutine_stopped()`. AFAIK we also have an indicator for with `unhandled_stopped`

**Comment by ericniebler** [comment]
No reason. I just didn't think of it!

**Comment by maikel** [comment]
This is done, right?

**Comment by ericniebler** [comment]
Yup
