### ISSUE TITLE
investigate why `"split move-only and copyable senders"` test hangs locally with nvc++

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#772]
Also `"split into when_all"`.

Happens locally, doesn't hang in CI. Tested with nvc++ 22.11+

**Comment by ccotter** [comment]
Interesting ... I haven't observed this, and just tried a gcc-12 build with ASAN, TSAN, UBSAN and didn't find anything (tests always passed locally). Curious what you find

**Comment by ericniebler** [comment]
The description is incomplete. It only happens with the nvc++ compiler. I suspect a codegen issue.

**Comment by maikel** [comment]
FWIW, I could reproduce it in the container image `nvcr.io/nvidia/nvhpc:22.11-devel-cuda11.8-ubuntu22.04`

**Comment by ericniebler** [comment]
This seems to be a codegen issue having something to do with `std::shared_ptr`. The address stored into the shared_ptr [here](https://github.com/NVIDIA/stdexec/blob/a3e1e91e576acf8c11009ec0f6b1192c4122059b/include/stdexec/execution.hpp#L3657) is not the same as the address pulled out of the shared_ptr [here](https://github.com/NVIDIA/stdexec/blob/a3e1e91e576acf8c11009ec0f6b1192c4122059b/include/stdexec/execution.hpp#L3603-L3604).

**Comment by ericniebler** [comment]
Confirmed that this is an nvc++ codegen issue having to do with the `[[no_unique_address]]` attribute. PR #894 disabled that attribute when compiling with nvc++. This issue is fixed.
