### ISSUE TITLE
Where is P2300R6 and P2300R7?

### ISSUE THREAD

**Issue by RishabhRD** [NVIDIA/stdexec#773]
I see references to P2300R6 and P2300R7 in some of commits and issues. But I can't find those papers on wg21. So, is there some other way of accessing those?

**Comment by villevoutilainen** [comment]
https://wg21.link/P2300R6 takes you to R6. There's no R7 yet in the paper system, so
you can see a rendered version of it at https://brycelelbach.github.io/wg21_p2300_execution/execution.html
and the sources at https://github.com/brycelelbach/wg21_p2300_execution
