### ISSUE TITLE
Failure to compile on Power due to __bool

### ISSUE THREAD

**Issue by williamspatrick** [NVIDIA/stdexec#787]
I had someone report that my code using stdexec didn't compile on a Power9 system.

```
__detail/__meta.hpp:71:7: error: expected identifier before '__attribute__'
    using __bool = std::bool_constant<_B>;
```

At first this looked a little confusing since there is no `__attribute__` here, but I think what is going on is that `__bool` is defined on Power as a compiler intrinsic (if that is the right word here).  See https://gcc.gnu.org/onlinedocs/gcc/PowerPC-AltiVec_002fVSX-Built-in-Functions.html :

> Compiling with -maltivec adds keywords __vector, vector, __pixel, pixel, __bool and bool. When compiling ISO C, the context-sensitive substitution of the keywords vector, pixel and bool is disabled. To use them, you must include <altivec.h> instead.

Should I send up a PR that changes all `__bool` to `__boolean` ?  Is there something else that should be used instead of `stdexec::__bool`.

**Comment by ericniebler** [comment]
> Should I send up a PR that changes all `__bool` to `__boolean` ?

I would gladly accept that patch.
