### ISSUE TITLE
difference between 'libunifex' and 'stdexec'

### ISSUE THREAD

**Issue by Runner-2019** [NVIDIA/stdexec#789]
I see there are two libraries that implements 'P2300R6' proposal, stdexec and libunifex。Though they are similiar in most situations, a little differences also exists. For example, 'libunifex' not support 'start_detached' API. So, what's the real difference  between libunifex and stdexec ?  Hope someone could give me some comparions :)

**Comment by OBorce** [comment]
some discussion on [Reddit](https://www.reddit.com/r/cpp/comments/zdogz9/comment/iz6lzc5/?utm_source=share&utm_medium=web2x&context=3)

**Comment by Runner-2019** [comment]
> some discussion on [Reddit](https://www.reddit.com/r/cpp/comments/zdogz9/comment/iz6lzc5/?utm_source=share&utm_medium=web2x&context=3)

thanks, that's maybe what I need. I'll carefully read it.

**Comment by villevoutilainen** [comment]
stdexec tracks the P2300 proposal (or vice versa, if you want to look at it that way), and they update hand-in-hand. libunifex is an earlier prototype, and is not kept up to date when changes are made to P2300 or its reference implementation, i.e. stdexec.
