### ISSUE TITLE
Propose scheduler queries for synchronization primitives (?)

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#842]
This is a suggestion from @dietmarkuehl. A strand scheduler might not want the algorithms to use locks and atomics for synchronization, for instance. Needs design work.

**Comment by smurzin** [comment]
Sorry was passing by - looks like there was an older issue identical to this one https://github.com/NVIDIA/stdexec/issues/690

**Comment by ericniebler** [comment]
Indeed. Thanks, closing as a dupe.
