### ISSUE TITLE
sender concept has side effects, is order-dependent

### ISSUE THREAD

**Issue by seanbaxter** [NVIDIA/stdexec#856]
https://github.com/NVIDIA/stdexec/blob/main/include/stdexec/execution.hpp#L752
The sender concept here is recursive and order dependent. It's the last thing preventing circle from building stdexec.

You can expose this in clang, just swap the order of the move_constructible constraint:
```cpp
  template <class _Sender, class _Env = no_env>
  concept sender =
    // NOT TO SPEC
    // The sender related concepts are temporarily "in flight" being
    // upgraded from P2300R5 to the get_env / enable_sender aware version
    // in P2300R7.
  
    move_constructible<remove_cvref_t<_Sender>> && //
    __sender<_Sender> &&                           //
    __sender<_Sender, _Env> &&                     //
    environment_provider<__cref_t<_Sender>> &&     //
    constructible_from<remove_cvref_t<_Sender>, _Sender>;
```
Then compile test/exec/test_any_sender.cpp. Clang produces an error message so long (5500 lines) that it ICEs itself.

```
 370833 - stdexec::move_constructible<exec::any_receiver_ref<stdexec::completion_signatures<stdexec::__receivers::set_value_t(int), stdexec::__receivers::set_error_t(std::__exception_ptr::exception_ptr)>>::any_sender<>> = 1*
          POTENTIAL CONCEPT VALUE VIOLATIONS:
            stdexec::sender<exec::any_receiver_ref<stdexec::completion_signatures<stdexec::__receivers::set_value_t(int), stdexec::__receivers::set_error_t(std::__exception_ptr::exception_ptr)>>::any_sender<>, stdexec::__env::no_env>
           308697 - stdexec::constructible_from<exec::any_receiver_ref<stdexec::completion_signatures<stdexec::__receivers::set_value_t(int), stdexec::__receivers::set_error_t(std::__exception_ptr::exception_ptr)>>::any_sender<>, exec::any_receiver_ref<stdexec::completion_signatures<stdexec::__receivers::set_value_t(int), stdexec::__receivers::set_error_t(std::__exception_ptr::exception_ptr)>>::any_sender<>> = 1*
             308647 - stdexec::destructible<exec::any_receiver_ref<stdexec::completion_signatures<stdexec::__receivers::set_value_t(int), stdexec::__receivers::set_error_t(std::__exception_ptr::exception_ptr)>>::any_sender<>> = 1*
             409048 - stdexec::__decays_to<exec::any_receiver_ref<stdexec::completion_signatures<stdexec::__receivers::set_value_t(int), stdexec::__receivers::set_error_t(std::__exception_ptr::exception_ptr)>>::any_sender<>, exec::any_receiver_ref<stdexec::completion_signatures<stdexec::__receivers::set_value_t(int), stdexec::__receivers::set_error_t(std::__exception_ptr::exception_ptr)>>::any_sender<>> = 1*
               308364 - stdexec::__std_concepts::__same_as<exec::any_receiver_ref<stdexec::completion_signatures<stdexec::__receivers::set_value_t(int), stdexec::__receivers::set_error_t(std::__exception_ptr::exception_ptr)>>::any_sender<>, exec::any_receiver_ref<stdexec::completion_signatures<stdexec::__receivers::set_value_t(int), stdexec::__receivers::set_error_t(std::__exception_ptr::exception_ptr)>>::any_sender<>> = 1*
             409057 - stdexec::sender<exec::any_receiver_ref<stdexec::completion_signatures<stdexec::__receivers::set_value_t(int), stdexec::__receivers::set_error_t(std::__exception_ptr::exception_ptr)>>::any_sender<>, stdexec::__env::no_env> = 0*
               370828 - stdexec::__sender<exec::any_receiver_ref<stdexec::completion_signatures<stdexec::__receivers::set_value_t(int), stdexec::__receivers::set_error_t(std::__exception_ptr::exception_ptr)>>::any_sender<>, stdexec::__env::no_env> = 1
               370833 - stdexec::move_constructible<exec::any_receiver_ref<stdexec::completion_signatures<stdexec::__receivers::set_value_t(int), stdexec::__receivers::set_error_t(std::__exception_ptr::exception_ptr)>>::any_sender<>> = 0
```

This is output from my concept trace. At the top, `stdexec::move_constructible<any_sender<>>` enters evaluation. The `stdexec::sender<any_sender<>>` concept reads out an improper value. Although though the type is move constructible, `stdexec::sender<any_sender<>>` evaluates `move_constructible` while that concept is being evaluated, so it yields up a `false` value, even though it is ultimately assigned a true value. `move_constructible` is evaluated as both a false and a true constant.

I think the fact that the trunk compiles with clang depends on some implementation-dependent, unspecified concept-evaluation logic.

**UPDATE:**
I located the recursion.
https://github.com/NVIDIA/stdexec/blob/main/include/exec/any_sender_of.hpp#L852

The `stdexec::sender<_Sender>` part of that constraint is recursive. Clang apparently does not evaluate that from inside the `__is_constructible` intrinsic when looking a move constructor for `any_sender<>`. Circle does consider that candidate as part of over.match.ctor. For `sender<any_sender<>>` to evaluate true, `any_sender<>` must be move-constructible, but we're inside the `stdexec::move_constructible` concept, and so it's false!

Likely clang is recognizing move ctor as a special case and short-circuiting consideration of non-special member functions inside `__is_constructible`.

**UPDATE2:**

I modified my over.match.ctor to consider other ctor candidates in the copy/move ctor case only when there isn't a copy/move special member function, and now that test compiles. So that is definitely the culprit.

**Comment by maikel** [comment]
Thank you for this report. How could I prevent this as author of `any_sender_of`? Are the constraints wrong on the constructor wrong? I happily admit that those recursions gave me headaches.

**Comment by ericniebler** [comment]
#857 ought to fix this. The problem is not in the sender concept, but in the implementation of `any_sender_of` here:

```c++
      template <__none_of<__t&, const __t&> _Tp>
        requires __callable<__create_vtable_t, __mtype<_Vtable>, __mtype<std::decay_t<_Tp>>>
      __t(_Tp&& __object)
```

https://github.com/NVIDIA/stdexec/blob/main/include/exec/any_sender_of.hpp#L307

The `__none_of` constraint is intended to prevent the `__callable` constraint from being evaluated for copy/move construction. But we're missing the move (rvalue reference) case. This fixes it:

```diff
-     template <__none_of<__t&, const __t&> _Tp>
+     template <__none_of<__t, __t&, const __t&> _Tp>
```

The context here is that `any_sender_of` should be constructible from types that satisfy `sender`, but `any_sender_of` _itself_ satisfies `sender`. We have to head off the concept recursion early, so that the converting constructor is not considered for copy/move construction.

**Comment by seanbaxter** [comment]
Can we just make recursive concept definitions ill-formed?

**Comment by ericniebler** [comment]
Hopefully, there aren't any recursive concept definitions now. There may still be recursive constraints like the one I just fixed. I don't know how or why this compiled with clang or gcc. Seems to me a hard error is preferable, like you suggest.

That's not my department, tho.
