### ISSUE TITLE
stdexec::sync_wait - several files are not getting built & couldnt run the examples

### ISSUE THREAD

**Issue by centi1** [NVIDIA/stdexec#935]
I tried to build this repo using MSVC compiler & i have given the steps i have done... 
I used c++23 latest of Visual studio. 

_C:\......\stdexec>cmake -S . -B build -G "Visual Studio 17 2022" -A x64
-- The CXX compiler identification is MSVC 19.36.32530.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Tools/MSVC/14.36.32530/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- System           : Windows-10.0.22621
-- System name      : Windows
-- System ver       : 10.0.22621
--
-- Library ver      : 0.8.0
-- Build date       : 2023-05-17
-- Build year       : 2023
--
-- CPM: adding package Catch2@2.13.6 (2.13.6)
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Configuring done (16.9s)
-- Generating done (0.3s)
-- Build files have been written to: C:/......./stdexec/build_

after compiling i used the below code to build & found series of files not built. 
_C:\L\stdexec>cmake --build build
MSBuild version 17.6.3+07e294721 for .NET Framework

  Checking Build System
  Building Custom Rule C:/..../stdexec/examples/CMakeLists.txt
  _clangd_helper_file.cpp
  example.clangd.helper.vcxproj -> C:\.....\stdexec\build\examples\Debug\example.clangd.helper.exe
  Building Custom Rule C:/...../stdexec/examples/CMakeLists.txt
  hello_coro.cpp
C:\.....\stdexec\include\stdexec\__detail\__config.hpp(19,1): fatal  error C1189: #error:  This library requires the use of
 C++20. [C:\.....\stdexec\build\examples\example.hello_coro.vcxproj]
  Building Custom Rule C:/...../stdexec/examples/CMakeLists.txt
  hello_world.cpp
C:\.....\stdexec\include\stdexec\__detail\__config.hpp(19,1): fatal  error C1189: #error:  This library requires the use of
 C++20. [C:\.....\stdexec\build\examples\example.hello_world.vcxproj]
  Building Custom Rule C:/...../stdexec/examples/CMakeLists.txt
  retry.cpp
C:\.....\stdexec\include\stdexec\__detail\__config.hpp(19,1): fatal  error C1189: #error:  This library requires the use of
 C++20. [C:\.....\stdexec\build\examples\example.retry.vcxproj]
  Building Custom Rule C:/...../stdexec/examples/CMakeLists.txt
  scope.cpp
.
.
.
the list goes on_

I am getting these seeries of failures stating I need C++20. But I have used the latest version C++23 for Visual studio. 

Could you please let me know where i am making mistake? I couldnt build the examples provided in this library & I could make use of the examples to build my own code as I am relatively new to C++.

Thank you...
![image](https://github.com/NVIDIA/stdexec/assets/65355093/ebc52acf-1d3d-4fb4-968a-489fa9845e81)

**Comment by ericniebler** [comment]
Microsoft's compiler is not one of the supported compilers. From the README:

```
Requirements
----

stdexec requires compiling with C++20 (`-std=c++20`) but otherwise does not have any dependencies and only requires a sufficiently new compiler:

clang 12+
gcc 11+
[nvc++ 22.11+](https://developer.nvidia.com/nvidia-hpc-sdk-releases) (required for [GPU support](https://github.com/NVIDIA/stdexec#gpu-support))
```
