### ISSUE TITLE
replace all remaining uses of `__x` with `__id`

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#944]
See discussion [here](https://github.com/NVIDIA/stdexec/blob/main/MAINTAINERS.md#class-template-parameters) for background

**Comment by sarthaknimbalkar** [comment]
Hey @ericniebler Can you please say what i exactly need to do here, I'm ready to give it a try.

**Comment by ericniebler** [comment]
Sure. There are places that use `__x` to hide a template parameter's associated namespaces. You'll see this pattern in code:

```c++
template <class ReceiverId>
struct xyz_receiver {
  using Receiver = stdexec::__t<ReceiverId>;
  // ... receiver implementation here
};

// ... later

template <class Receiver>
xyz_receiver< stdexec::__x<Receiver> > make_xyz_receiver(Receiver rcvr) {...
```

With `__x`, the code needs to become:

```c++
template <class ReceiverId>
struct xyz_receiver {
  using Receiver = stdexec::__t<ReceiverId>;

  struct __t {
    using __id = xyz_receiver;
    // receiver implementation here...
  };
};

// ... later

template <class Receiver>
stdexec::__t< xyz_receiver< stdexec::__id<Receiver> > > make_xyz_receiver(Receiver rcvr) {...
```

Replacing `__x` with `__id` this way improves the quality of diagnostics by making nested sender types shorter and less noisy, and so easier to read.

Thanks for offering to help!

**Comment by sarthaknimbalkar** [comment]
Woahh, that's neat !!!
Can you provide me with a head start? I simply want to know which files require modifications, then I'll get going.
Thank you.

**Comment by ericniebler** [comment]
You could start with `include/exec/async_scope.hpp`.

**Comment by sarthaknimbalkar** [comment]
Okay It'll do.
Thanks
