### ISSUE TITLE
track down problem in the CUDA stream implementation of `bulk`

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#953]
See the `nvexec/reduce` example in the [`nvexec-bulk-bug`](https://github.com/NVIDIA/stdexec/pull/new/nvexec-bulk-bug) branch for a repro, or just run the tests.

Attached is a dump from `compute-sanitizer`.

[error.log](https://github.com/NVIDIA/stdexec/files/11608471/error.log)

**Comment by senior-zero** [comment]
Reproducer from the branch:
```cpp
      // ...
  |   stdexec::let_value(
          [](std::span<double> out){ return stdexec::just(out); }) 
  |   stdexec::bulk(nelems,
          [](std::size_t i, std::span<double> out){ out[i] = 2.0 * out[i]; }); 
```

What's happening on the implementation side: 
- gpu: invokes `return stdexec::just(out);` 
- cpu: copies resulting sender from gpu to cpu
- cpu: connects resulting sender and starts operation state
- cpu: stdexec::just operation state passes rvalue reference to completion channel
- cpu: nvexec::bulk invokes kernel with lvalue reference to span stored in cpu memory
- gpu: nvexec::bulk kernel accesses lvalue reference to span stored in cpu memory -> issue

**Comment by ericniebler** [comment]
> cpu: copies resulting sender from gpu to cpu

Where in the code is that copy happening?

**Comment by senior-zero** [comment]
> > cpu: copies resulting sender from gpu to cpu
> 
> Where in the code is that copy happening?

It's happening in the pointer [dereferencing](https://github.com/NVIDIA/stdexec/blob/5e0b6a595fa8812881889662150d6fd2ebf49c17/include/nvexec/stream/let_xxx.cuh#L118-L122) after stream synchronization.

**Comment by ericniebler** [comment]
> Reproducer from the branch:
> 
> ```c++
>       // ...
>   |   stdexec::let_value(
>           [](std::span<double> out){ return stdexec::just(out); }) 
>   |   stdexec::bulk(nelems,
>           [](std::size_t i, std::span<double> out){ out[i] = 2.0 * out[i]; }); 
> ```
> 
> What's happening on the implementation side:
> 
> * gpu: invokes `return stdexec::just(out);`
> * cpu: copies resulting sender from gpu to cpu
> * cpu: connects resulting sender and starts operation state
> * cpu: `stdexec::just` operation state passes rvalue reference to completion channel
> * cpu: `nvexec::bulk` invokes kernel with lvalue reference to `span` stored in cpu memory
> * gpu: `nvexec::bulk` kernel accesses lvalue reference to `span` stored in cpu memory -> issue

@senior-zero, thanks. At each step here, the types are doing reasonable things, IMO. I can imagine this sort of thing happening a lot. What do you think about storing the whole operation state in pinned memory rather than on the (host) stack in `sync_wait`?

**Comment by senior-zero** [comment]
@ericniebler I think storing the operation state in pinned memory should fix the issue.

**Comment by ericniebler** [comment]
once we have all the operation states in pinned memory (needs to be done also for `split` and `ensure_started`), then all the little bits of temp storage we allocate in pinned memory can become data members of the operation state, saving a significant number of allocations.

**Comment by senior-zero** [comment]
@ericniebler I don't think this is the goal for all senders. If we consider `then(return_val) | then(accept_val)`, I'd expect there to be no host/device traffic. If the temporary storage for then return value is in pinned memory, every access from GPU is going to happen through PCIe.
